title: ""
description: "Stella's Journey: a narrative path through solitude and hope. Amrita Express project." 
baseurl: "/amrita-express"
url: "https://stellaboschi.io"

# Parametri per il Footer (Auto-aggiornante)
start_year: 2017
copyright_name: "Stella Boschi"
